### ISSUE TITLE
Application does not have correct permissions

### ISSUE THREAD

**Issue by jimix** [Appdynamics/ECommerce-Android#5]
[ECommerce-Android/app/src/main/AndroidManifest.xml](https://github.com/Appdynamics/ECommerce-Android/blob/master/app/src/main/AndroidManifest.xml#L12) is missing the following permission at line 12:
```
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

Without it, phones that obey it (not all do) will result in network connection information being published as "unknown"

**Comment by mqprichard** [comment]
Thanks Jimi - fixed
